In [3]:
import sympy as sp
import numpy as np
import math
import collections
import tqdm
import itertools
import random
from loguru import logger

import utils

In [2]:
enum = enumeration.Enumerator(10**8, 10**5)

  0%|          | 0/100000 [00:00<?, ?it/s]

100%|██████████| 4784/4784 [00:00<00:00, 88658.13it/s]


In [4]:
enum.enumerate_radius_factorized(sp.factorint(2 * 5 * 13 * 17))

[(43, 19), (37, 29), (47, 1), (41, 23)]
[[43 19]
 [37 29]
 [47  1]
 [41 23]]


In [5]:
len(enum.primes)

4784

In [20]:
x = np.zeros((5, 8))
hits = np.zeros((5, 3), dtype=np.int32)

x[np.arange(5)[:, None], hits]

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
x[:] = 0
x

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])